nelmio_api_doc:
    documentation:
        openapi: '3.0.0'
        info:
            title: BileMoAPI
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
        paths:
            /api/login_check:
                post:
                    tags:
                        - Login
                    summary: Login into the api
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        username:
                                            type: string
                                            example: firstCustomer
                                        password:
                                            type: string
                                            example: password
                                    type: object
                    responses:
                        '200':
                            description: Get the Bearer token to log in the API
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Bad Json syntax or incorrect data
                    security: []
            /api/doc.json:
                get:
                    tags:
                        - Documentation
                    summary: Get doc
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
